name: Periodic health check

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          if: github.event.schedule == '5 * * * *'
          url: https://wispy-sun-5820.fly.dev/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
